version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: smart_mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: smart_canteen
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    # 必须更换为 redis-stack-server，它内置了 LangChain4j 需要的向量搜索模块
    image: redis/redis-stack-server:latest
    container_name: smart_redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    # 如果你 application.yml 里 redis 没填密码，这里去掉 --requirepass 部分
    # 如果要密码，依然可以加上：command: redis-server --requirepass 123456


  mongodb:
    image: mongo:6
    container_name: smart_mongo
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db

  minio:
    image: minio/minio
    container_name: smart_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./docker/minio/data:/data
    command: server /data --console-address ":9001"