package com.holly.aliyun;

public class RiskLabel {

    //文本风险标签
    public static final String[] textRiskLabels = {
            "pornographic_adult",
            "sexual_terms",
            "sexual_suggestive",
            "political_figure",
            "political_entity",
            "political_n",
            "political_p",
            "political_a",
            "violent_extremist",
            "violent_incidents",
            "violent_weapons",
            "contraband_drug",
            "contraband_gambling",
            "contraband_act",
            "contraband_entity",
            "inappropriate_discrimination",
            "inappropriate_ethics",
            "inappropriate_profanity",
            "inappropriate_oral",
            "inappropriate_superstition",
            "inappropriate_nonsense",
            "pt_to_sites",
            "pt_by_recruitment",
            "pt_to_contact",
            "religion_b",
            "religion_t",
            "religion_c",
            "religion_i",
            "religion_h",
            "customized"
    };

    //图片风险标签
    public static final String[] imagesRiskLabels = {
            "pornographic_adultContent",
            "pornographic_adultContent_tii",
            "sexual_suggestiveContent",
            "sexual_partialNudity",
            "political_politicalFigure",
            "political_politicalFigure_name_tii",
            "political_politicalFigure_metaphor_tii",
            "political_TVLogo",
            "political_map",
            "political_outfit",
            "political_prohibitedPerson",
            "political_prohibitedPerson_tii",
            "political_taintedCelebrity",
            "political_taintedCelebrity_tii",
            "political_flag",
            "political_historicalNihility",
            "political_historicalNihility_tii",
            "political_religion_tii",
            "political_racism_tii",
            "political_badge",
            "violent_explosion",
            "violent_gunKnives",
            "violent_gunKnives_tii",
            "violent_armedForces",
            "violent_crowding",
            "violent_horrorContent",
            "violent_horric_tii",
            "contraband_drug",
            "contraband_drug_tii",
            "contraband_gamble",
            "contraband_gamble_tii",
            "fraud_videoAbuse",
            "fraud_playerAbuse"
    };
}